spring:
  application:
    name: 08-springboot-DATABASE-2
  datasource:
    dbcp2:
      driver-class-name: oracle.jdbc.driver.OracleDriver
    password: system
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: system
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
